import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { UI_TOKENS, CHART_PALETTES, THEMES } from './tokens.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'public', 'css');
mkdirSync(outDir, { recursive: true });

let css = `/* Generated by scripts/gen-tokens.mjs — do not edit by hand. Source: scripts/tokens.mjs */\n`;

for (const theme of THEMES) {
  const t = UI_TOKENS[theme];
  const lines = Object.entries(t).map(([k, v]) => `  --${k}: ${v};`);
  const chart = CHART_PALETTES[theme]
    .map((v, i) => `  --chart-${i + 1}: ${v};`)
    .join('\n');
  const sel =
    theme === 'light'
      ? `:root, [data-theme='light'] {`
      : `[data-theme='${theme}'] {`;
  css += `\n${sel}\n${lines.join('\n')}\n${chart}\n}\n`;
}

writeFileSync(join(outDir, 'tokens.css'), css);
console.log('wrote', join('public', 'css', 'tokens.css'));
